### ISSUE TITLE
Running regression tests on Linux requires srun

### ISSUE THREAD

**Issue by rachelwaldon** [LLNL/quandary#24]
@srkohn 

User story: I want to run the regression tests to verify install on a Linux machine.

Current behavior: see screenshots 
Regression tests fail on Linux machine in this case Ubuntu 22.04.3 LTS that don't use srun. It would be better if regression tests use something more general for users not explicitly using LC machines.
![regression_tests_quandary_1](https://github.com/LLNL/quandary/assets/42785514/b1545a33-250e-487d-8e0d-8e6c7967a7fc)
![quandary_regression_tests_2](https://github.com/LLNL/quandary/assets/42785514/ca315bd6-0ef3-45ea-b170-2f78f5e8d49d)
![quandary_tests_results_AxC_adjoint_log](https://github.com/LLNL/quandary/assets/42785514/298b5651-07a2-4fa2-84a2-12e5cb884ebc)

**Comment by steffi7574** [comment]
The commit 9cf1343c6e54 should solve this issue.
