### ISSUE TITLE
Number of subsystems

### ISSUE THREAD

**Issue by relugzosiraba** [LLNL/quandary#6]
Thanks for your work. Quandary looks promising.

How many subsystems can Quandary handle? Juqbox can handle 3 subsystems at most. I am wondering if there is any such limitation for Quandary at the moment.

**Comment by steffi7574** [comment]
Hi! Thanks for your interest! 

Quandary can in principle handle any number of subsystems (as long as you have enough compute power), but you will have to choose the sparse-matrix solver for linear algebra if you are considering more than two subsystems.  

You can choose the number of oscillators and their modeled number of energy levels through the option 'nlevels' in the configuration file, and you will have to set the option 'usematfree=false' if you are using more than two subsystems. 

I'm happy to assist setting up a configuration file for a specific test case, if you are interested in trying out Quandary for your application!

**Comment by relugzosiraba** [comment]
Thanks! 

One of the cases I am interested in is to create gates on cavity modes controlled via a transmon. Each mode (including transmon) is a subsystem. Is there an example I can find about this within the repo? I know you have similar interests (https://arxiv.org/abs/2106.09148). Are there configuration files available for the tests in https://github.com/LLNL/quandary/tree/master/tests? It would be good to start with running some of those tests.
