### ISSUE TITLE
Parameter sweep with Quandary

### ISSUE THREAD

**Issue by relugzosiraba** [LLNL/quandary#9]
There is a sample Slurm script here: https://github.com/LLNL/quandary/blob/master/util/slurm_script.

How should it be modified to do parameter sweep over configuration options?

`SLURM_PROCID` can be useful as a variable for the sweep. How should it be used in .cfg files?

Let’s say we have a list of “transfreq” to be used in each .cfg file:

```
transfreq_1 = 4416.66, 6840.815
transfreq_2 = 4500.66, 6900.815
transfreq_3 = 4700.66, 7000.81
```

There are 3 in this example but many will be needed. We can combine them into a single array (format may vary), such as

`transfreq_array = [[4416.66, 6840.815], [4500.66, 6900.815], [4700.66, 7000.815]],`

and use `SLURM_PROCID` for each instance.

What is the correct format for such arrays to be used in .cfg files of Quandary jobs?

Is it possible/recommended to use a single .cfg file for the parameter sweep? Or should we use a separate .cfg file for each set of configuration parameters?

**Comment by steffi7574** [comment]
When Quandary parses the .cfg file, it looks for "transfeq" and expects a list of transition frequencies per oscillator. It throws an error if the list is not in this format (list with Q elements, Q being the number of oscillators). 
When sweeping over parameters, you could modify the python script [https://github.com/LLNL/quandary/blob/master/util/submit_scalingstudy.py](https://github.com/LLNL/quandary/blob/master/util/submit_scalingstudy.py) for your needs (I've tried it with Python2 only). You can choose the parameters to sweep over, and it will generate separate .cfg files for each case in separate folders, as well as a slurm script to submit a job for it.

**Comment by relugzosiraba** [comment]
I saw the python script. Thanks for updating it.
